### ISSUE TITLE
Dataset and How to use the code

### ISSUE THREAD

**Issue by caijiaping** [jonathanrjpereira/Smart-Energy-Monitor#3]
HI there,

I am a master of data science student. Currently I am working on a project of smart meter monitor (electricity disaggregation).  I am interested in your coding. Since I am a Python beginner and there are so many folders in your posting could you please advise how I can learn your scripts step by step?
Meanwhile, could you please advise what dataset you used?

Your kindly help will be appreciated.

Many thanks 
Jacky

**Comment by jonathanrjpereira** [comment]
I'm currently in the process of cleaning up the code & making it easier for one to make the Smart Energy Monitor. I also plan on adding the hardware schematics. As of now **SimBox3** has the latest code; although it is not the final code. I still have to commit the final code. It will take a few weeks to do so but hopefully, it should be ready before November.

I created my own dataset based on the values I measured using the hardware setup.

**Comment by caijiaping** [comment]
Thanks for your prompt reply. Is it possible that you can share the dataset structure with me? I have a dataset from my client including timestamp and Watt per minute. Unfortunately, I have no idea what I should do to start for disaggregation analysis. In your code tab, could you please advise which script I can start to explore?
